### ISSUE TITLE
Animation Skeleton/snippet

### ISSUE THREAD

**Issue by nirlipo** [planimation/plugins#1]
Christian suggested adding a skeleton similar to the code snippets ([see this example in editor](http://editor.planning.domains/#edit_session=M19r6Y47MI4V4wf))

Two ways of doing this:
1. Can add a bare skeleton with the main sections of animation profiles
2. Given a PDDL domain, generate a skeleton with the predicates, leaving the __effects__ section of predicates to be filled out

**Comment by haz** [comment]
Actually, 1 would be _extremely_ easy: in the initialization function, run `window.add_snippet(snippet, trigger);`. You can find more info on the snippet syntax [[here](https://cloud9-sdk.readme.io/docs/snippets)]

For example, the trigger `"action"` is used for the following snippet (not going to properly escape the string, but you get the point):
```
	(:action ${1:actionName}
	    :parameters (?x - type)
	    :precondition (and (foo ?x))
	    :effect (and
	        (fuu ?x)
	        (not (fiu ?x ?x))
	    )
	)
```

**Comment by haz** [comment]
A more complete example that's relevant...

```javascript
var snippet = '';
snippet += '(:predicate ${1:predicateName}\n';
snippet += '   :parameters (?x ?y)\n';
snippet += '   :priority 0\n';
snippet += '   :effect( ... )\n';
snippet += ')';
window.add_snippet(snippet, "predicate");
```

Put this (or similar) in the `initialize` function somewhere, and you should be good to go.

**Comment by nirlipo** [comment]
That's great!

just created this [pull-request in bitbucket](https://bitbucket.org/planning-researchers/planimation/pull-requests/1/adding-snippets-animation-and-predicate/diff)

Commit in this repo can be reviewed here: [6b6fd57]
